parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\DataFixtures\:
        resource: '../src/DataFixtures/'
        tags: ['doctrine.fixture.orm']

    App\Event\UserVerificationSubscriber:
        tags:
            - { name: 'kernel.event_subscriber' }

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/DataFixtures'

    app.event_listener.custom_jwt_created_listener:
        class: App\Event\CustomJWTCreatedListener
        arguments: [ '@request_stack' ]
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }
    
    App\Doctrine\CurrentUserExtension:
        tags:
            - { name: api_platform.doctrine.orm.query_extension.collection }
            - { name: api_platform.doctrine.orm.query_extension.item }